name: Test-Mysql
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
    steps:
    - name: mysql port
      run: echo ${PORT}
      env:
        PORT: ${{ job.services.mysql.ports['3306']}}
    - name: mysql init script
      run: mysql --help
    - name: run scripts
      run: ls initdb/*.sql | sort | xargs cat | mysql -uroot -proot -P ${PORT} --host mysql
    - name: query
      run: echo "SELECT COUNT(*) from repositories;" | mysql -uroot -proot -P ${PORT} --host mysql